# Meta Data for SEO

## Homepage
title = "OpenPPG Config"
titleSeparator = "-"
titleAddition = "Config Tool for OpenPPG"
description = "Easily adjust settings on your OpenPPG X4 or OpenPPG SP140"

## Open Graph + Twitter Cards
images = ["gear-icon.png"]
twitterSite = "openppg"
twitterCreator = "openppg"
ogLocale = "en_US"

## Social Media (replaces deprecated .Site.Social)
[Social]
twitter = "openppg"
# facebook = "your-facebook-page"
# facebook_admin = "your-facebook-admin-id"

## Author (replaces deprecated .Site.Authors)
[Author]
name = "OpenPPG"
# [Author.Social]
# twitter = "openppg"
# facebook = "your-facebook-profile"

## JSON-LD
schemaType = "Organization"
schemaLogo = "gear-icon.png"
schemaTwitter = "https://twitter.com/openppg"
schemaLinkedIn = "https://www.linkedin.com/in/openppg/"
schemaGitHub = "https://github.com/openppg"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Want more updates? <a class=\"alert-link\" href=\"https://twitter.com/openppg\">Follow us on Twitter</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/openppg/openppg-config-v2"
editPage = false
